import { Card } from "@/components/ui/card"
import { motion } from "framer-motion"
import type { Variants } from "framer-motion"
import { CheckCircle2, Code2, Shield } from "lucide-react"

const steps = [
  {
    icon: Code2,
    title: "Detect AI Code",
    description: "Identify code generated by AI models with advanced pattern recognition",
  },
  {
    icon: Shield,
    title: "Scan for Vulnerabilities",
    description: "Run comprehensive security checks against OWASP Top 10 and custom rules",
  },
  {
    icon: CheckCircle2,
    title: "Auto-Fix Issues",
    description: "Generate and apply security patches automatically to your codebase",
  },
]

export function HowItWorks() {
  const containerVariants: Variants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
        delayChildren: 0.1,
      },
    },
  }

  const cardVariants: Variants = {
    hidden: { opacity: 0, y: 50 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        type: "spring",
        stiffness: 300,
        damping: 30,
      },
    },
  }

  return (
    <section id="how-it-works" className="relative py-24 overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
            How <span className="text-green-500">vibecheck</span> Works
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Three simple steps to secure your AI-generated code
          </p>
        </motion.div>

        {/* Cards Grid */}
        <motion.div
          className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12"
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
        >
          {steps.map((step, index) => {
            const Icon = step.icon
            return (
              <motion.div 
                key={index} 
                variants={cardVariants}
                whileHover={{ y: -8, scale: 1.02 }}
                transition={{ duration: 0.3 }}
              >
                <Card className="h-full p-8 border-green-500/10 hover:border-green-500/40 hover:bg-green-500/5 hover:shadow-xl hover:shadow-green-500/20 transition-all duration-300 group">
                  <div className="relative mb-6">
                    <div className="inline-flex p-3 rounded-lg bg-green-500/10 group-hover:bg-green-500/20 group-hover:scale-110 transition-all duration-300">
                      <Icon className="h-6 w-6 text-green-500 group-hover:text-green-400 transition-colors duration-300" />
                    </div>
                    <div className="absolute -top-2 -right-2 h-8 w-8 rounded-full bg-gradient-to-r from-green-500 to-green-600 text-black flex items-center justify-center text-xs font-bold group-hover:scale-125 group-hover:shadow-lg group-hover:shadow-green-500/50 transition-all duration-300">
                      {index + 1}
                    </div>
                  </div>
                  <h3 className="text-xl font-semibold mb-3 group-hover:text-green-500 transition-colors duration-300">{step.title}</h3>
                  <p className="text-muted-foreground">{step.description}</p>
                </Card>
              </motion.div>
            )
          })}
        </motion.div>

        {/* Connecting Line (Desktop Only) */}
        <svg className="hidden md:block w-full h-12 mb-8" viewBox="0 0 1200 50" preserveAspectRatio="none">
          <line x1="0" y1="25" x2="1200" y2="25" stroke="url(#gradient)" strokeWidth="2" strokeDasharray="5,5" />
          <defs>
            <linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%" stopColor="#ef4444" stopOpacity="0.3" />
              <stop offset="50%" stopColor="#a855f7" stopOpacity="0.3" />
              <stop offset="100%" stopColor="#ef4444" stopOpacity="0.3" />
            </linearGradient>
          </defs>
        </svg>
      </div>
    </section>
  )
}
