import { Card } from "@/components/ui/card"
import { motion } from "framer-motion"
import type { Variants } from "framer-motion"
import { CheckCircle2, Code2, Shield } from "lucide-react"

const steps = [
  {
    icon: Code2,
    title: "Detect AI Code",
    description: "Identify code generated by AI models with advanced pattern recognition",
  },
  {
    icon: Shield,
    title: "Scan for Vulnerabilities",
    description: "Run comprehensive security checks against OWASP Top 10 and custom rules",
  },
  {
    icon: CheckCircle2,
    title: "Auto-Fix Issues",
    description: "Generate and apply security patches automatically to your codebase",
  },
]

export function HowItWorks() {
  const containerVariants: Variants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
        delayChildren: 0.1,
      },
    },
  }

  const cardVariants: Variants = {
    hidden: { opacity: 0, y: 50 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        type: "spring",
        stiffness: 300,
        damping: 30,
      },
    },
  }

  return (
    <section id="how-it-works" className="relative py-24 overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
            How <span className="text-green-500">vibecheck</span> Works
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Three simple steps to secure your AI-generated code
          </p>
        </motion.div>

        <motion.div
          className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12"
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
        >
          {steps.map((step, index) => {
            const Icon = step.icon
            return (
              <motion.div 
                key={index} 
                variants={cardVariants}
                whileHover={{ y: -6 }}
                transition={{ duration: 0.25 }}
              >
                <Card className="h-full p-7 border-border/60 bg-background/60 hover:border-green-500/70 hover:bg-green-500/5 hover:shadow-lg hover:shadow-green-500/20 transition-all duration-300 group">
                  <div className="mb-4 flex items-center justify-between">
                    <div className="inline-flex h-9 w-9 items-center justify-center rounded-lg bg-green-500/10 text-green-500 group-hover:bg-green-500/15">
                      <Icon className="h-5 w-5" />
                    </div>
                    <span className="rounded-full border border-border/60 bg-background/80 px-3 py-1 text-xs font-medium text-muted-foreground group-hover:border-green-500/60 group-hover:text-green-400">
                      Step {index + 1}
                    </span>
                  </div>
                  <h3 className="text-lg font-semibold mb-2 group-hover:text-green-500 transition-colors duration-300">
                    {step.title}
                  </h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    {step.description}
                  </p>
                </Card>
              </motion.div>
            )
          })}
        </motion.div>

        <div className="hidden md:block w-full h-px bg-gradient-to-r from-transparent via-green-500/30 to-transparent mb-4" />
      </div>
    </section>
  )
}
